apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mybfbob-com
  namespace: cert-manager
spec:
  # Secret names are always required.
  secretName: mybfbob-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
  - mybfbob.com
  - www.mybfbob.com
  - core.mybfbob.com
  ipAddresses:
  - 35.196.253.44
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
